#!/bin/bash
# C2Trap - Complete Setup Guide (From Scratch)

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║         C2Trap - Complete Setup From Scratch              ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

echo "Follow these steps to get C2Trap running:"
echo ""
echo "1️⃣  START ALL SERVICES (First Time Setup)"
echo "   Run this to build and start all Docker containers:"
echo "   $ ./C2Trap"
echo ""
echo "   This will:"
echo "   • Build all Docker images"
echo "   • Start all containers (dashboard, decoys, analysis engines)"
echo "   • Display the dashboard URL"
echo ""

echo "2️⃣  LAUNCH THE DASHBOARD (Subsequent Runs)"
echo "   After initial setup, just run:"
echo "   $ ./scripts/dashboard.sh"
echo ""
echo "   This will show:"
echo "   • Which containers are starting"
echo "   • Dashboard URL: http://localhost:8000"
echo ""

echo "3️⃣  GENERATE ATTACK TRAFFIC"
echo "   Open a NEW terminal and run:"
echo "   $ ./scripts/attack.sh"
echo ""
echo "   Select intensity (1=Low, 2=Medium, 3=High)"
echo ""

echo "4️⃣  MONITOR LIVE TRAFFIC (Optional)"
echo "   Open ANOTHER terminal and run:"
echo "   $ ./scripts/monitor.sh"
echo ""

echo "5️⃣  VIEW THE DASHBOARD"
echo "   Open your browser:"
echo "   http://localhost:8000"
echo ""
echo "   The dashboard will auto-refresh every 5 seconds!"
echo ""

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                      QUICK REFERENCE                      ║"
echo "╠═══════════════════════════════════════════════════════════╣"
echo "║  Start Everything:    ./C2Trap                            ║"
echo "║  Dashboard Only:      ./scripts/dashboard.sh              ║"
echo "║  Generate Traffic:    ./scripts/attack.sh                 ║"
echo "║  Monitor Live:        ./scripts/monitor.sh                ║"
echo "║                                                           ║"
echo "║  Dashboard URL:       http://localhost:8000               ║"
echo "╚═══════════════════════════════════════════════════════════╝"
